### ISSUE TITLE
MVP 0.2

### ISSUE THREAD

**Issue by mihok** [minimalchat/daemon#14]
The focus for 0.2 is to be "Open Source ready" aka, Show HN post.

# Milestones

- [x] Emit `client:typing` and `operator:typing` events to the right sockets (#21)
- [x] Remembering clients, handing chat history back to the client (#20)
- [x] Initial step into storage engines (#8)
- [x] Support SSL (#25)
- [x] Create Issue template (#6)
- [x] Create `CONTRIBUTING.md` (#26)

**Comment by mihok** [comment]
Done.
