### ISSUE TITLE
MVP 0.1

### ISSUE THREAD

**Issue by mihok** [minimalchat/daemon#7]
MVP Plan for the API/Socket Daemon.

Following the [API spec](https://github.com/minimalchat/mnml-daemon/wiki/API-Spec) from the Wiki, the MVP push is to get basic functionality.

# 0.1
### Global
- [x] Listen for socket connections on base route `/`

### Clients
- [x] If incoming connection comes from a website, create a Client (#12)

### Operators
- [x] If incoming connection comes from an Operator app, create an Operator (#12)

### Clients
- [x] ~~Create client (POST) `/api/client`~~
- [x] ~~Update client (POST/PUT/PATCH) `/api/client/:CLIENT_ID`~~
- [x] Get client (GET) `/api/client/:CLIENT_ID`
- [x] Get client**s** (GET) `/api/clients`
- [x] ~~Delete client (DELETE) `/api/client/:CLIENT_ID`~~

### Chats
- [x] ~~Create chat (POST) `/api/chat`~~
- [x] ~~Update chat (POST/PUT/PATCH) `/api/chat/:CHAT_ID`~~
- [x] Get chat (GET) `/api/chat/:CHAT_ID`
- [x] Get chat**s** (GET) `/api/chats`
- [x] ~~Delete client (DELETE) `/api/chat/:CHAT_ID`~~
- [x] Add `open` Boolean field to chat object (#13)

### Chat Messages
- [x] Create message (POST) `/api/chat/:CHAT_ID/message`
- [x] ~~Update message (POST/PUT/PATCH) `/api/chat/:CHAT_ID/message/:MSG_ID`~~
- [x] ~~Get message (GET) `/api/chat/:CHAT_ID/message/:MSG_ID`~~
- [x] Get messages**s** (GET) `/api/chat/:CHAT_ID/messages`
- [x] ~~Delete client (DELETE) `/api/chat/:CHAT_ID`~~

### Operators
- [x] Create client (POST) `/api/operator`
- [x] Update client (POST/PUT/PATCH) `/api/operator/:OPERATOR_ID`
- [x] Get client (GET) `/api/operator/:OPERATOR_ID`
- [x] Get client**s** (GET) `/api/operators`
- [x] Delete client (DELETE) `/api/operator/:OPERATOR_ID`
